// console.log("*****Ejemplo estructura de manejo de ERRORES:estructura => try-catch-finaly***** ")

// try {
//     console.log("En el try se agrega el códio a evaluar.")
//     error
//     console.log("Segundo mensaje en el try.")

// } catch (error) {
//     console.log("Catch captura cualquier error surgido o lanzado en el try.")
// } finally {
//     console.log("El bloque finaly, se ejecutará siempre al final de un bloque try-catch.")
// }



// try {
//     let number = "23";

//     if (isNaN(number)) {
//         throw new Error("El carácter introducido no es un Número")
//     }
//     console.log(number * number)

// } catch (error) {
//     console.log(`Se produjo el siguiete error:${error}`)
// }









